# Site wide configuration

title: MagiCarbon
locale: en_US
description: The Magic Carbon. LOL~
logo: site-logo.gif
search: true
url: https://magicarbon.github.io/mc #http://MagiCarbon.github.io


# Jekyll configuration

permalink: /:categories/:year/:month/:day/:title.html
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false
  input: GFM
  # syntax_highlighter: rouge #for local

mathjax: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor", "serve.sh"]

paginate: 15
paginate_path: posts/page:num

# Site owner
owner:
  name: MagiCarbon
  avatar: site-logo.gif
  email: MagiCarbon@gmail.com
  disqus-shortname: MagiCarbon
  twitter: MagiCarbon
  facebook: MagiCarbon
  github: MagiCarbon
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: MagiCarbon
  flickr: #username
  tumblr: MagiCarbon
  pinterest: #username
  weibo: #userid
  google:
    plus: MagiCarbon
    analytics: #UA-54877893-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  cnzz: '<script type="text/javascript" src="http://s11.cnzz.com/z_stat.php?id=1256712738&web_id=1256712738"></script>'
